### ISSUE TITLE
Instance Methods

### ISSUE THREAD

**Issue by J7mbo** [GaryJones/php-type-converter#2]
Although this is an old repo and doesn't look maintained, I'm just going to log an issue before forking it and making it as I need it.

The code is great, it works as expected, but the fact that everything is static is a major issue - I can't mock this out in the latest version of PHPUnit during my unit tests - we shouldn't be using static methods **at all** - it's 2015 now man :P

Anyway, I'll fork and do the work to change, will PR but if no response I'll put on Packagist myself as I need to use this repo :-)

**Comment by GaryJones** [comment]
Thanks for the PR. 

Yes, it is an old repo, but I don't actively maintain it. It was for a project that got cancelled.

I'm happy to transfer the GitHub to you if you want. If you register it on Packagist, I'll then Abandon mine and recommend yours. Just let me know.

**Comment by J7mbo** [comment]
Hey Gary, just realised - you were at PHPSC weren't you?? I've been using this lib for a few weeks now, small world... :-)

I'll upload onto packagist with credit to you.

**Comment by GaryJones** [comment]
> you were at PHPSC weren't you?

Yes, I was there :-) Small world indeed!

I've initiated the GitHub transfer of the repo to you. Not sure how long it will take, especially if you already have a fork, but any Packagist reference should be updated too.
